package com.ghostid.app.domain.model

enum class PlatformCategory { COMMUNICATION, SOCIAL, PROFESSIONAL, EMAIL }

enum class Platform(
    val displayName: String,
    val category: PlatformCategory,
    val signupUrl: String,
    val appDeepLink: String?,
    val usernameHint: String,
    val requiresPhone: Boolean,
) {
    SIGNAL(
        displayName = "Signal",
        category = PlatformCategory.COMMUNICATION,
        signupUrl = "https://signal.org/install/",
        appDeepLink = "sgnl://",
        usernameHint = "@username.01",
        requiresPhone = true,
    ),
    TELEGRAM(
        displayName = "Telegram",
        category = PlatformCategory.COMMUNICATION,
        signupUrl = "https://web.telegram.org/",
        appDeepLink = "tg://resolve",
        usernameHint = "@username",
        requiresPhone = true,
    ),
    DISCORD(
        displayName = "Discord",
        category = PlatformCategory.COMMUNICATION,
        signupUrl = "https://discord.com/register",
        appDeepLink = null,
        usernameHint = "username",
        requiresPhone = false,
    ),
    WHATSAPP(
        displayName = "WhatsApp",
        category = PlatformCategory.COMMUNICATION,
        signupUrl = "https://web.whatsapp.com/",
        appDeepLink = "whatsapp://",
        usernameHint = "phone number",
        requiresPhone = true,
    ),
    MATRIX(
        displayName = "Matrix/Element",
        category = PlatformCategory.COMMUNICATION,
        signupUrl = "https://app.element.io/#/register",
        appDeepLink = null,
        usernameHint = "@user:matrix.org",
        requiresPhone = false,
    ),
    INSTAGRAM(
        displayName = "Instagram",
        category = PlatformCategory.SOCIAL,
        signupUrl = "https://www.instagram.com/accounts/emailsignup/",
        appDeepLink = "instagram://",
        usernameHint = "@username",
        requiresPhone = false,
    ),
    TWITTER(
        displayName = "Twitter/X",
        category = PlatformCategory.SOCIAL,
        signupUrl = "https://twitter.com/i/flow/signup",
        appDeepLink = "twitter://",
        usernameHint = "@handle",
        requiresPhone = true,
    ),
    BLUESKY(
        displayName = "Bluesky",
        category = PlatformCategory.SOCIAL,
        signupUrl = "https://bsky.app/",
        appDeepLink = "bluesky://",
        usernameHint = "@handle.bsky.social",
        requiresPhone = false,
    ),
    MASTODON(
        displayName = "Mastodon",
        category = PlatformCategory.SOCIAL,
        signupUrl = "https://mastodon.social/auth/sign_up",
        appDeepLink = null,
        usernameHint = "@user@mastodon.social",
        requiresPhone = false,
    ),
    TIKTOK(
        displayName = "TikTok",
        category = PlatformCategory.SOCIAL,
        signupUrl = "https://www.tiktok.com/signup",
        appDeepLink = "tiktok://",
        usernameHint = "@username",
        requiresPhone = true,
    ),
    REDDIT(
        displayName = "Reddit",
        category = PlatformCategory.SOCIAL,
        signupUrl = "https://www.reddit.com/register/",
        appDeepLink = "reddit://",
        usernameHint = "u/username",
        requiresPhone = false,
    ),
    TUMBLR(
        displayName = "Tumblr",
        category = PlatformCategory.SOCIAL,
        signupUrl = "https://www.tumblr.com/register",
        appDeepLink = null,
        usernameHint = "username",
        requiresPhone = false,
    ),
    PINTEREST(
        displayName = "Pinterest",
        category = PlatformCategory.SOCIAL,
        signupUrl = "https://www.pinterest.com/register/",
        appDeepLink = null,
        usernameHint = "username",
        requiresPhone = false,
    ),
    LINKEDIN(
        displayName = "LinkedIn",
        category = PlatformCategory.PROFESSIONAL,
        signupUrl = "https://www.linkedin.com/signup/",
        appDeepLink = "linkedin://",
        usernameHint = "name-suffix",
        requiresPhone = false,
    ),
    GITHUB(
        displayName = "GitHub",
        category = PlatformCategory.PROFESSIONAL,
        signupUrl = "https://github.com/signup",
        appDeepLink = null,
        usernameHint = "username",
        requiresPhone = false,
    ),
    EMAIL_PROTON(
        displayName = "Email (Proton)",
        category = PlatformCategory.EMAIL,
        signupUrl = "https://account.proton.me/mail/signup",
        appDeepLink = "protonmail://",
        usernameHint = "user@proton.me",
        requiresPhone = false,
    ),
    EMAIL_TUTA(
        displayName = "Email (Tuta)",
        category = PlatformCategory.EMAIL,
        signupUrl = "https://app.tuta.com/signup",
        appDeepLink = null,
        usernameHint = "user@tuta.com",
        requiresPhone = false,
    ),
    EMAIL_DISROOT(
        displayName = "Email (Disroot)",
        category = PlatformCategory.EMAIL,
        signupUrl = "https://user.disroot.org/pwm/public/newuser",
        appDeepLink = null,
        usernameHint = "user@disroot.org",
        requiresPhone = false,
    ),
}
